workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop"'

default:
  image: gradle:8.14-jdk21

stages:
#  - lint_stage
  - test_stage
  - build_and_push_stage
  - build_and_publish_shared-lib_stage
#  - deploy_dev_stage
#  - deploy_prod_stage

include:
#  - local: '.gitlab/templates/lint_stage.yml'
  - local: '.gitlab/templates/test_stage.yml'
  - local: '.gitlab/templates/build_and_push_stage.yml'
  - local: '.gitlab/templates/build_and_publish_shared-lib_stage.yml'
#  - local: '.gitlab/templates/deploy_dev_stage.yml'
#  - local: '.gitlab/templates/deploy_prod_stage.yml'


