global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'category-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['category-service:9092']

  - job_name: 'compilation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['compilation-service:9093']

  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-service:8001']

  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-service:9091']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8989']

  - job_name: 'registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['registry:8761']

  - job_name: 'request-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['request-service:9094']

  - job_name: 'statistics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['statistics-service:9095']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:9090']

