--liquibase formatted sql

--changeset faspix:1
CREATE TABLE event_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id VARCHAR(50) NOT NULL,
    event_id BIGINT NOT NULL,
    creation_date TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_event
        FOREIGN KEY(event_id)
        REFERENCES events(event_id) ON DELETE CASCADE
);

--changeset faspix:2
ALTER TABLE events
    ADD COLUMN likes INTEGER NOT NULL DEFAULT 0;