--liquibase formatted sql

--changeset faspix:1
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id VARCHAR(50) NOT NULL,
    event_id BIGINT NOT NULL,
    text VARCHAR(2000) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_event
        FOREIGN KEY(event_id)
        REFERENCES events(event_id) ON DELETE CASCADE
);