services:

  config-service:
    restart: unless-stopped
    build: ../config-service
    depends_on:
      - postgresdb
    networks:
      - backend

  registry:
    restart: unless-stopped
    build: ../registry
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    networks:
      - backend

  category-service:
    restart: unless-stopped
    build: ../category-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  compilation-service:
    restart: unless-stopped
    build: ../compilation-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  event-service:
    restart: unless-stopped
    build: ../event-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  gateway:
    restart: unless-stopped
    build: ../gateway
    ports:
      - "8989:8989"
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  request-service:
    restart: unless-stopped
    build: ../request-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  statistics-service:
    restart: unless-stopped
    build: ../statistics-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  user-service:
    restart: unless-stopped
    build: ../user-service
    depends_on:
      - registry
      - config-service
    networks:
      - backend

  postgresdb:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - "7744:5432"
    environment:
#      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgresdb-data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    restart: unless-stopped
    environment:
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresdb:5432/user_service
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    depends_on:
      - postgresdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - keycloak-data:/opt/keycloak/data
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - backend

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  nexus:
    image: sonatype/nexus3:3.78.2
    restart: unless-stopped
    ports:
      - "8231:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2g

  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - backend

  logstash:
    image: logstash:8.17.1
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./config/logstash.conf:/logstash_dir/pipeline/logstash.conf
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - '5044:5044'
    depends_on:
      - elasticsearch
    networks:
      - backend

  kibana:
    image: kibana:8.17.1
    container_name: kibana
    restart: unless-stopped
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.53.4
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - backend

volumes:
  redis-data:
    driver: local
  postgresdb-data:
    driver: local
  keycloak-data:
    driver: local
  nexus-data:
    driver: local
  elastic-data:
    driver: local
  grafana-data:
    driver: local

networks:
  backend:
    driver: bridge