server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 100000