spring:
  application:
    name: registry
  config:
      import: configserver:http://config-service:8001
  cloud:
    config:
      fail-fast: true
      password: admin
      username: user


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 1000