keycloak:
  server-url: http://keycloak:7080
  realm: master
  client-id: admin-cli
  admin-username: admin
  admin-password: admin

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:7080/realms/master