logging:
  level:
    org.springframework.security: DEBUG

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

server:
  port: 0