spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/category_service
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: redis
      port: 6379
      password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    cache-names: redis-cache
  cloud:
    function:
      definition: updateCategoryNameProduce;
    stream:
      bindings:
        updateCategoryNameProduce-out-0:
          destination: update-category-name-dest
      kafka:
        binder:
          brokers: kafka:9025

server:
  port: 9092