spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/event_service
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: redis
      port: 6379
      password:
  cache:
    type: redis
    cache-names: redis-cache
  elasticsearch:
    uris: http://elasticsearch:9200
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: newConfirmedRequestConsume; endpointStatisticsProduce
    stream:
      bindings:
        newConfirmedRequestConsume-in-0:
          destination: confirmed-request-dest
          group: confirmed-request-group
          consumer:
            max-attempts: 3
        endpointStatisticsProduce-out-0:
          destination: endpoint-stats-dest
      kafka:
        binder:
          brokers: kafka:9025
        bindings:
          newConfirmedRequestConsume-in-0:
            consumer:
              enableDlq: true
              dlqName: newConfirmedRequestConsume-dead-letter-topic
              autoCommitOnError: false
              retryAttempts: 3
              backOffInitialInterval: 1000
              backOffMaxInterval: 5000

server:
  port: 9091
