spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/event_service
    username: postgres
    password: root
  data:
    jdbc:
      dialect: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: newConfirmedRequestConsume; endpointStatisticsProduce
    stream:
      bindings:
        newConfirmedRequestConsume-in-0:
          destination: confirmed-request-dest
          group: confirmed-request-group
        endpointStatisticsProduce-out-0:
          destination: endpoint-stats-dest

server:
  port: 9091
