spring:
  cloud:
    function:
      definition: notificationConsume
    stream:
      bindings:
        notificationConsume-in-0:
          destination: notification-dest
          group: notification-group
          consumer:
            max-attempts: 3
      kafka:
        binder:
          brokers: kafka:9025
        bindings:
          notificationConsume-in-0:
            consumer:
              enableDlq: true
              dlqName: notificationConsume-dead-letter-topic
              autoCommitOnError: false
              retryAttempts: 3
              backOffInitialInterval: 1000
              backOffMaxInterval: 5000

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
app:
  mail:
    from: email@gmail.com

server:
  port: 8080
