spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:7744/statistics_service
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: endpointStatisticsConsume
    stream:
      bindings:
        endpointStatisticsConsume-in-0:
          destination: endpoint-stats-dest
          group: endpoint-stats-group
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          endpointStatisticsConsume-in-0:
            consumer:
              deadLetterQueueName: endpoint-stats.dlq
              republishToDlq: true

server:
  port: 9095
