spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/statistics_service
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: endpointStatisticsConsume
    stream:
      bindings:
        endpointStatisticsConsume-in-0:
          destination: endpoint-stats-dest
          group: endpoint-stats-group
          consumer:
            max-attempts: 3
      kafka:
        binder:
          brokers: kafka:9025
        bindings:
          endpointStatisticsConsume-in-0:
            consumer:
              enableDlq: true
              dlqName: endpointStatisticsConsume-dead-letter-topic
              autoCommitOnError: false
              retryAttempts: 3
              backOffInitialInterval: 1000
              backOffMaxInterval: 5000

server:
  port: 9095
