spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresdb:5432/user_service
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: redis
      port: 6379
      password:
  cache:
    type: redis
    cache-names: redis-cache
  cloud:
    function:
      definition: updateUsernameProduce;
    stream:
      bindings:
        updateUsernameProduce-out-0:
          destination: update-username-dest
      kafka:
        binder:
          brokers: kafka:9025

server:
  port: 9090
