--liquibase formatted sql

--changeset faspix:1
CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE,
    state VARCHAR(255) NOT NULL,
    CONSTRAINT requests_state_check
        CHECK ((state)::TEXT = ANY
               ((ARRAY ['PENDING'::CHARACTER VARYING,
                   'CONFIRMED'::CHARACTER VARYING,
                   'REJECTED'::CHARACTER VARYING])::TEXT[]))

);


