spring:
  application:
    name: request-service
  config:
    import: configserver:http://config-service:8001
  cloud:
    config:
      fail-fast: true
      password: admin
      username: user
  profiles:
    active: rabbit, keycloak, keycloak-m2m