spring:
  application:
    name: event-service
  config:
    import: configserver:http://localhost:8001
  cloud:
    config:
      uri: http://localhost:8001
      fail-fast: true
      password: admin
      username: user
  profiles:
    active: rabbit, keycloak, keycloak-m2m, redis
