name: Build and Push Docker Images

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - master

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build without test
        run: |
          ./gradlew build -x test \
          -PREPOSITORY_USERNAME=${{ env.REPOSITORY_USERNAME }} \
          -PREPOSITORY_PASSWORD=${{ env.REPOSITORY_PASSWORD }} \
          -PREPOSITORY_URL=${{ vars.REPOSITORY_URL }}

      - name: Generate services list
        id: set-matrix
        run: |
          echo "Parsing settings.gradle..."
          services=$(grep "^include" settings.gradle | sed "s/include '//;s/'//")
          services=$(echo "$services" | grep -v '^shared-lib$')
          json=$(printf '%s\n' "$services" | jq -R . | jq -s -c .)
          echo "services=$json" >> $GITHUB_OUTPUT

      - name: Show generated matrix
        run: echo "${{ steps.set-matrix.outputs.services }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: '*/build/libs/'

  build-images-and-push:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.generate-matrix.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.service }}:pr-${{ github.event.pull_request.number }} ./${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.service }}:pr-${{ github.event.pull_request.number }}
