name: Tests Services

permissions:
  contents: read

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: |
          ./gradlew test \
          -PREPOSITORY_USERNAME=${{ secrets.GITHUB_ACTOR }} \
          -PREPOSITORY_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
          -PREPOSITORY_URL=${{ vars.REPOSITORY_URL }}


      - name: Generate coverage report
        run: |
          ./gradlew jacocoRootReport \
          -PREPOSITORY_USERNAME=${{ secrets.GITHUB_ACTOR }} \
          -PREPOSITORY_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
          -PREPOSITORY_URL=${{ vars.REPOSITORY_URL }}

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3
        with:
          coverage-reports: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
