name: Publish common-dto

on:
  push:
    branches:
      - master

jobs:
  publish-common-dto:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Nexus Container
        run: |
          docker run -d -p 8081:8081 --name nexus sonatype/nexus3:3.78.2
          for i in {1..30}; do
            if curl -s http://localhost:8081 > /dev/null; then
              echo "Nexus is up!"
              break
            fi
            sleep 10
          done
          if ! curl -s http://localhost:8081 > /dev/null; then
            echo "Nexus failed to start in time"
            exit 1
          fi

      - name: Get Nexus Admin Password
        run: |
          PASSWORD=$(docker exec nexus cat /nexus-data/admin.password)
          echo "REPOSITORY_USERNAME=admin" >> $GITHUB_ENV
          echo "REPOSITORY_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish common-dto to Nexus
        run: |
          cd common-dto
          ./../gradlew publish 
          -PrepositoryUsername=${{ env.REPOSITORY_USERNAME }}
          -PrepositoryPassword=${{ env.REPOSITORY_PASSWORD }}