name: Test Microservices

on:
  push:
    branches:
      - master

jobs:
  publish-common-dto:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Nexus Container
        run: |
          docker run -d -p 8231:8081 --name nexus sonatype/nexus3:3.78.2
          for i in {1..30}; do
            if curl -s http://localhost:8231 > /dev/null; then
              echo "Nexus is up!"
              break
            fi
            sleep 10
          done
          if ! curl -s http://localhost:8231 > /dev/null; then
            echo "Nexus failed to start in time"
            exit 1
          fi

      - name: Get Nexus Admin Password
        run: |
          PASSWORD=$(docker exec nexus cat /nexus-data/admin.password)
          echo "REPOSITORY_USERNAME=admin" >> $GITHUB_ENV
          echo "REPOSITORY_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "repository_username=admin" >> $GITHUB_OUTPUT
          echo "repository_password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Accept EULA and set initial password
        run: |
          curl -u $REPOSITORY_USERNAME:$REPOSITORY_PASSWORD -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "disclaimer": "Use of Sonatype Nexus Repository - Community Edition is governed by the End User License Agreement at https://links.sonatype.com/products/nxrm/ce-eula. By returning the value from ‘accepted:false’ to ‘accepted:true’, you acknowledge that you have read and agree to the End User License Agreement at https://links.sonatype.com/products/nxrm/ce-eula.",
              "accepted": true
              }' \
            http://localhost:8231/service/rest/v1/system/eula

      - name: Create eventhub-shared-lib Repository
        run: |
          curl -u ${{ env.REPOSITORY_USERNAME }}:${{ env.REPOSITORY_PASSWORD }} -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "name": "eventhub-shared-lib",
                  "online": true,
                  "storage": {
                    "blobStoreName": "default",
                    "strictContentTypeValidation": true,
                    "writePolicy": "ALLOW"
                  },
                  "maven": {
                    "versionPolicy": "RELEASE",
                    "layoutPolicy": "STRICT",
                    "contentDisposition": "INLINE"
                  },
                  "type": "hosted",
                  "format": "maven2"
                }' \
            http://localhost:8231/service/rest/v1/repositories/maven/hosted

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish common-dto to Nexus
        run: |
          cd common-dto
          ./../gradlew publish \
          -PREPOSITORY_WRITE_USERNAME=${{ env.REPOSITORY_USERNAME }} \
          -PREPOSITORY_WRITE_PASSWORD=${{ env.REPOSITORY_PASSWORD }}

  test-microservices:
    needs: publish-common-dto
    runs-on: ubuntu-latest

    env:
      REPOSITORY_USERNAME: ${{ needs.job1.outputs.repository_username }}
      REPOSITORY_PASSWORD: ${{ needs.job1.outputs.repository_password }}

    steps:
      - name: test2
        run: |
          echo $REPOSITORY_USERNAME
          echo $REPOSITORY_PASSWORD
